server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:6542/ewm-stats
    username: stats
    password: stats
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    ru.practicum.stats: debug
